language: node_js
node_js:
  - "node"
  - "7"
  - "6"
before_script:
  - npm install -g codecov istanbul mocha
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
  - npm test